### ISSUE TITLE
After attempting to switch workspaces using the shortcut, BinkyBox shuts down.

### ISSUE THREAD

**Issue by lkmnch** [nadimkobeissi/binkybox#2]
Hi, 
I wanted to use this Tool but unfortunately it doesn't work for me.

After I input the shortcut the program shuts down

I use Windows 11 Pro Version 22H2.

**Comment by lkmnch** [comment]
It works now, thank you!

**Comment by nadimkobeissi** [comment]
@lkmnch This was fixed in [BinkyBox 0.2.0](https://github.com/nadimkobeissi/binkybox/releases/tag/v0.2.0), please consider updating.
