### ISSUE TITLE
Modifier keys not in the shortcut aren't checked to make sure they are not pressed

### ISSUE THREAD

**Issue by banburybill** [nadimkobeissi/binkybox#5]
If you set up a shortcut LCTRL+1 and then press LCRTL+LSHIFT+1, the shortcut will trigger erroneously. binkybox currently checks only that shortcut keys are down.

**Comment by nadimkobeissi** [comment]
PR welcome.

**Comment by nadimkobeissi** [comment]
@banburybill This was fixed in [BinkyBox 0.2.0](https://github.com/nadimkobeissi/binkybox/releases/tag/v0.2.0), please consider updating.
