### ISSUE TITLE
When trying to switch to a workspace that does not exist, BlinkyBox shuts down

### ISSUE THREAD

**Issue by lkmnch** [nadimkobeissi/binkybox#6]
When I press the shortcut for a workspace that doesn't exist, the programm shuts down. 

Maybe this action could create a new workspace?

**Comment by nadimkobeissi** [comment]
@lkmnch This was fixed in [BinkyBox 0.2.0](https://github.com/nadimkobeissi/binkybox/releases/tag/v0.2.0), please consider updating.
